export const AUTHORIZE = 'AUTHORIZE'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_INVALIDATE = 'AUTH_INVALIDATE'

export const CHANGE_ROUTE = 'router/ROUTE_CHANGED'

export const FORM_RECOMMEND_COMPANY_REQUEST = 'FORM_RECOMMEND_COMPANY_REQUEST'
export const FORM_RECOMMEND_COMPANY_SUCCESS = 'FORM_RECOMMEND_COMPANY_SUCCESS'
export const FORM_RECOMMEND_WORKER_REQUEST = 'FORM_RECOMMEND_WORKER_REQUEST'
export const FORM_RECOMMEND_WORKER_SUCCESS = 'FORM_RECOMMEND_WORKER_SUCCESS'
export const FORM_FAILURE = 'FORM_FAILURE'
