export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_HIDE = 'ALERT_HIDE'

export const AUTHORIZE = 'AUTHORIZE'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_INVALIDATE = 'AUTH_INVALIDATE'

export const CHANGE_ROUTE = 'router/ROUTE_CHANGED'

export const FORM_RECOMMEND_COMPANY_REQUEST = 'forms/RECOMMEND_COMPANY_REQUEST'
export const FORM_RECOMMEND_COMPANY_SUCCESS = 'forms/RECOMMEND_COMPANY_SUCCESS'
export const FORM_RECOMMEND_COMPANY_FAILURE = 'forms/RECOMMEND_COMPANY_FAILURE'

export const FORM_RECOMMEND_WORKER_REQUEST = 'forms/RECOMMEND_WORKER_REQUEST'
export const FORM_RECOMMEND_WORKER_SUCCESS = 'forms/RECOMMEND_WORKER_SUCCESS'
export const FORM_RECOMMEND_WORKER_FAILURE = 'forms/RECOMMEND_WORKER_FAILURE'

export const FORM_REGISTER_USER_REQUEST = 'forms/REGISTER_USER_REQUEST'
export const FORM_REGISTER_USER_SUCCESS = 'forms/REGISTER_USER_SUCCESS'
export const FORM_REGISTER_USER_FAILURE = 'forms/REGISTER_USER_FAILURE'

export const RECEIVE_RECOMMENDATIONS = 'RECEIVE_RECOMMENDATIONS'
export const RECEIVE_ALL_PERMISSIONS = 'RECEIVE_ALL_PERMISSIONS'
